# site settings
title: Nilava
subtitle: Hi!
email: nilavachowdhury99@gmail.com
description: Hi! My name is Nilava
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nilavachowdhury.github.io"
author:
street_address: 148, Dum Dum Park
city: Kolkata
state: West Bengal
zip_code: 700055
country: India
phone: (+91) 90077-49184

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
